CREATE TABLE `bookings` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text NOT NULL,
	`event_date` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`phrase` text NOT NULL,
	`service` text NOT NULL,
	`fulfillment` text NOT NULL,
	`zip` text,
	`floor` text,
	`elevator` text,
	`customer_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`event_type` text,
	`venue` text,
	`display_location` text,
	`notes` text,
	`total` real NOT NULL,
	`amount_paid` real DEFAULT 0 NOT NULL,
	`payment_status` text DEFAULT 'Unpaid' NOT NULL,
	`status` text DEFAULT 'New request' NOT NULL,
	`letter_count` integer NOT NULL
);
