import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const bookings = sqliteTable("bookings", {
  id: text("id").primaryKey(),
  createdAt: text("created_at").notNull(),
  eventDate: text("event_date").notNull(),
  startTime: text("start_time").notNull(),
  endTime: text("end_time").notNull(),
  phrase: text("phrase").notNull(),
  service: text("service").notNull(),
  fulfillment: text("fulfillment").notNull(),
  address: text("address"),
  address2: text("address_2"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  deliveryMiles: real("delivery_miles"),
  deliveryFee: real("delivery_fee"),
  floor: text("floor"),
  elevator: text("elevator"),
  customerName: text("customer_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  eventType: text("event_type"),
  venue: text("venue"),
  displayLocation: text("display_location"),
  notes: text("notes"),
  total: real("total").notNull(),
  amountPaid: real("amount_paid").notNull().default(0),
  paymentStatus: text("payment_status").notNull().default("Unpaid"),
  status: text("status").notNull().default("New request"),
  letterCount: integer("letter_count").notNull(),
});

export const stripeSettings = sqliteTable("stripe_settings", {
  id: text("id").primaryKey(),
  activeMode: text("active_mode").notNull().default("test"),
  testPublishableKey: text("test_publishable_key"),
  testSecretKeyEncrypted: text("test_secret_key_encrypted"),
  testWebhookSecretEncrypted: text("test_webhook_secret_encrypted"),
  livePublishableKey: text("live_publishable_key"),
  liveSecretKeyEncrypted: text("live_secret_key_encrypted"),
  liveWebhookSecretEncrypted: text("live_webhook_secret_encrypted"),
  updatedAt: text("updated_at").notNull(),
});

export const bookingDrafts = sqliteTable("booking_drafts", {
  id: text("id").primaryKey(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  currentStep: integer("current_step").notNull().default(1),
  status: text("status").notNull().default("In progress"),
  email: text("email"),
  customerName: text("customer_name"),
  total: real("total").notNull().default(0),
  data: text("data").notNull(),
  bookingId: text("booking_id"),
});

export const paymentAttempts = sqliteTable("payment_attempts", {
  id: text("id").primaryKey(),
  bookingId: text("booking_id").notNull(),
  draftId: text("draft_id"),
  stripeSessionId: text("stripe_session_id"),
  mode: text("mode").notNull(),
  amount: real("amount").notNull(),
  status: text("status").notNull(),
  error: text("error"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});
